http:
  port: "8081"
  
sfdc:
  username: "cnanjappa@open-logix.com"
  password: "Chethanhn3@"
  token: "kqw13yl1m01JCr3FCy7hFF842"
  
file:
  accountsDir: "C:/Users/cheth/Downloads/APDevFundamentals_studentFiles_SP_04may2023/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"
